services:
#### MONGO DB
  dbmongo:  # nombre para ejecucion -> docker-compose up -d dbmongo
    image: mongo:5.0  # nombre de la imagen:version
    container_name: ${ALIAS}_mongo   # nombre que tendra dentro del contendor
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./${ALIAS}_mongo:/data/db   # aqui se guarda en la ruta raiz del archivo en la carpeta: ./db_mongo
    # restart: always
    logging:  # control de log para guardar
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    network_mode: "databases"
# volumes:
#   mongo_data:
# networks:
#   - databases

#### MYSQL
  dbmysql:
    image: mysql:8.3.0
    container_name: ${ALIAS}_mysql
    env_file: .env
    tty: true
    ports:
      - "3307:3306"
    # restart: always
    volumes:
      - ./${ALIAS}_mysql:/var/lib/mysql
    environment:
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_USER: ${DATABASE_USER}
    network_mode: "databases"

#### POSTGRESQL
  dbpostgres:
    image: postgres:15
    container_name: ${ALIAS}_postgres
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      # - POSTGRES_DB=mydb
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./${ALIAS}_pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    # restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    network_mode: "databases"

#### MSSQL
  # dbmssql:
  #   image: mcr.microsoft.com/mssql/server:2014-latest

  dbsqlserver:
    image: mcr.microsoft.com/mssql/server:2014-latest
    container_name: ${ALIAS}_sqlserver
    environment:
      - SA_PASSWORD=MyStrongPassword
      - ACCEPT_EULA=Y
    volumes:
      - ./${ALIAS}_sqlserverdata:/var/opt/mssql/data
    ports:
      - "1434:1433"
    # restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    network_mode: "databases"