name: confluent_kafka

# crear previamente el network: kafka-confluent
# docker network create --attachable kafka-confluent

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.7.1
    container_name: cp-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - kafka-confluent

  kafka:
    image: confluentinc/cp-kafka:7.7.1
    container_name: cp-kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    networks:
      - kafka-confluent
    entrypoint: ["sh", "-c", "sleep 30 && /etc/confluent/docker/run"]

  control-center:
    image: confluentinc/cp-enterprise-control-center:7.7.1
    container_name: cp-control-center
    depends_on:
      - kafka
      - zookeeper
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'kafka:9092'
      CONTROL_CENTER_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      CONTROL_CENTER_CONNECT_CLUSTER: 'connect'
      CONTROL_CENTER_KSQL_URL: "http://ksql-server:8088"
      CONTROL_CENTER_KSQL_ADVERTISED_URL: "http://ksql-server:8088"
      CONTROL_CENTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      CONTROL_CENTER_REPLICATION_FACTOR: 1
    ports:
      - "9021:9021"
    networks:
      - kafka-confluent
    entrypoint: ["sh", "-c", "sleep 120 && /etc/confluent/docker/run"]

networks:
  kafka-confluent:
    external: true