name: hcd
# HashiCorp Developer -> hcd
# docker-compose up -d

services:
  vault:
    image: hashicorp/vault:1.18.2
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
      - VAULT_CONFIG_DIR=/vault/config
    # restart: unless-stopped
    volumes:
      - ./vault-config:/vault/config
    cap_add:
      - IPC_LOCK
    network_mode: "databases"
    command: vault server -config=/vault/config/vault.hcl